#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jul 16, 2026 12:16:06 AM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
# --- BUNDLED GAME ROUTER ---
import os
if len(sys.argv) >= 3 and sys.argv[1] == "RUN_GAME":
    game_name = sys.argv[2]
    os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
    # Mapping filenames to internal modules
    games = {
        "space_game.py": "space_game", "flappy_hand.py": "flappy_hand",
        "bubble_pop.py": "bubble_pop", "tictactoe.py": "tictactoe",
        "dance_game.py": "dance_game", "breaker.py": "breaker",
        "hammer_game.py": "hammer_game", "test_tracking.py": "test_tracking",
        "debug_husky.py": "debug_husky"
    }
    try:
        if game_name in games: __import__(games[game_name])
    except Exception as e: print(f"Error loading {game_name}: {e}")
    sys.exit()
# ---------------------------

import HuskyArcade_support

_bgcolor = 'black'
_fgcolor = 'white'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: HuskyArcade_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'page-dark.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('clam') # <--- THIS IS THE ONLY CHANGE
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("991x615+448+254")
        top.minsize(176, 1)
        top.maxsize(1924, 1050)
        top.resizable(1,  1)
        top.title("HuskyLensV2 Arcade")
        top.configure(background="black")
        top.configure(highlightbackground="black")
        top.configure(highlightcolor="white")

        self.top = top
        self.combobox = tk.StringVar()
        self.combobox.set('TCombobox')

        self.Label_Connected = tk.Label(self.top)
        self.Label_Connected.place(relx=0.071, rely=0.163, height=31, width=107)
        self.Label_Connected.configure(activebackground="#d9d9d9")
        self.Label_Connected.configure(activeforeground="black")
        self.Label_Connected.configure(anchor='w')
        self.Label_Connected.configure(background="black")
        self.Label_Connected.configure(compound='left')
        self.Label_Connected.configure(disabledforeground="#3f3f3f")
        self.Label_Connected.configure(foreground="white")
        self.Label_Connected.configure(highlightbackground="black")
        self.Label_Connected.configure(highlightcolor="white")

        _style_code()
        self.TCombobox_PortSelector = ttk.Combobox(self.top)
        self.TCombobox_PortSelector.place(relx=0.182, rely=0.163, relheight=0.05
                , relwidth=0.112)
        self.TCombobox_PortSelector.configure(exportselection="0")
        self.TCombobox_PortSelector.configure(textvariable=self.combobox)

        self.btn_Dodge = tk.Button(self.top)
        self.btn_Dodge.place(relx=0.373, rely=0.146, height=54, width=238)
        self.btn_Dodge.configure(activebackground="#d9d9d9")
        self.btn_Dodge.configure(activeforeground="black")
        self.btn_Dodge.configure(background="black")
        self.btn_Dodge.configure(compound='left')
        self.btn_Dodge.configure(disabledforeground="#3f3f3f")
        self.btn_Dodge.configure(foreground="white")
        self.btn_Dodge.configure(highlightbackground="black")
        self.btn_Dodge.configure(highlightcolor="white")
        self.btn_Dodge.configure(text='''Space Dodge''')

        self.btn_Hands = tk.Button(self.top)
        self.btn_Hands.place(relx=0.373, rely=0.244, height=54, width=238)
        self.btn_Hands.configure(activebackground="#d9d9d9")
        self.btn_Hands.configure(activeforeground="black")
        self.btn_Hands.configure(background="black")
        self.btn_Hands.configure(compound='left')
        self.btn_Hands.configure(disabledforeground="#3f3f3f")
        self.btn_Hands.configure(foreground="white")
        self.btn_Hands.configure(highlightbackground="black")
        self.btn_Hands.configure(highlightcolor="white")
        self.btn_Hands.configure(text='''Flappy Hand''')

        self.btn_pop = tk.Button(self.top)
        self.btn_pop.place(relx=0.373, rely=0.341, height=54, width=238)
        self.btn_pop.configure(activebackground="#d9d9d9")
        self.btn_pop.configure(activeforeground="black")
        self.btn_pop.configure(background="black")
        self.btn_pop.configure(compound='left')
        self.btn_pop.configure(disabledforeground="#3f3f3f")
        self.btn_pop.configure(foreground="white")
        self.btn_pop.configure(highlightbackground="black")
        self.btn_pop.configure(highlightcolor="white")
        self.btn_pop.configure(text='''Husky Pop''')

        self.Btn_TacToe = tk.Button(self.top)
        self.Btn_TacToe.place(relx=0.373, rely=0.439, height=54, width=238)
        self.Btn_TacToe.configure(activebackground="#d9d9d9")
        self.Btn_TacToe.configure(activeforeground="black")
        self.Btn_TacToe.configure(background="black")
        self.Btn_TacToe.configure(compound='left')
        self.Btn_TacToe.configure(disabledforeground="#3f3f3f")
        self.Btn_TacToe.configure(foreground="white")
        self.Btn_TacToe.configure(highlightbackground="black")
        self.Btn_TacToe.configure(highlightcolor="white")
        self.Btn_TacToe.configure(text='''Husky TacToe''')

        self.btn_Dance = tk.Button(self.top)
        self.btn_Dance.place(relx=0.373, rely=0.537, height=54, width=238)
        self.btn_Dance.configure(activebackground="#d9d9d9")
        self.btn_Dance.configure(activeforeground="black")
        self.btn_Dance.configure(background="black")
        self.btn_Dance.configure(compound='left')
        self.btn_Dance.configure(disabledforeground="#3f3f3f")
        self.btn_Dance.configure(foreground="white")
        self.btn_Dance.configure(highlightbackground="black")
        self.btn_Dance.configure(highlightcolor="white")
        self.btn_Dance.configure(text='''Husky Dance''')

        self.btn_Braker = tk.Button(self.top)
        self.btn_Braker.place(relx=0.373, rely=0.634, height=54, width=238)
        self.btn_Braker.configure(activebackground="#d9d9d9")
        self.btn_Braker.configure(activeforeground="black")
        self.btn_Braker.configure(background="black")
        self.btn_Braker.configure(compound='left')
        self.btn_Braker.configure(disabledforeground="#3f3f3f")
        self.btn_Braker.configure(foreground="white")
        self.btn_Braker.configure(highlightbackground="black")
        self.btn_Braker.configure(highlightcolor="white")
        self.btn_Braker.configure(text='''Husky Breaker''')

        self.btn_Hammer = tk.Button(self.top)
        self.btn_Hammer.place(relx=0.373, rely=0.732, height=54, width=238)
        self.btn_Hammer.configure(activebackground="#d9d9d9")
        self.btn_Hammer.configure(activeforeground="black")
        self.btn_Hammer.configure(background="black")
        self.btn_Hammer.configure(compound='left')
        self.btn_Hammer.configure(disabledforeground="#3f3f3f")
        self.btn_Hammer.configure(foreground="white")
        self.btn_Hammer.configure(highlightbackground="black")
        self.btn_Hammer.configure(highlightcolor="white")
        self.btn_Hammer.configure(text='''Husky Hammer''')

        self.btn_Camera = tk.Button(self.top)
        self.btn_Camera.place(relx=0.373, rely=0.829, height=54, width=238)
        self.btn_Camera.configure(activebackground="#d9d9d9")
        self.btn_Camera.configure(activeforeground="black")
        self.btn_Camera.configure(background="black")
        self.btn_Camera.configure(compound='left')
        self.btn_Camera.configure(disabledforeground="#3f3f3f")
        self.btn_Camera.configure(foreground="white")
        self.btn_Camera.configure(highlightbackground="black")
        self.btn_Camera.configure(highlightcolor="white")
        self.btn_Camera.configure(text='''Test Camera''')

        self.btn_Exit = tk.Button(self.top)
        self.btn_Exit.place(relx=0.373, rely=0.927, height=44, width=238)
        self.btn_Exit.configure(activebackground="#d9d9d9")
        self.btn_Exit.configure(activeforeground="black")
        self.btn_Exit.configure(background="black")
        self.btn_Exit.configure(compound='left')
        self.btn_Exit.configure(disabledforeground="#3f3f3f")
        self.btn_Exit.configure(foreground="white")
        self.btn_Exit.configure(highlightbackground="black")
        self.btn_Exit.configure(highlightcolor="white")
        self.btn_Exit.configure(text='''Close''')

        self.Label_Maker = tk.Label(self.top)
        self.Label_Maker.place(relx=0.797, rely=0.959, height=31, width=197)
        self.Label_Maker.configure(activebackground="#d9d9d9")
        self.Label_Maker.configure(activeforeground="black")
        self.Label_Maker.configure(anchor='w')
        self.Label_Maker.configure(background="black")
        self.Label_Maker.configure(compound='left')
        self.Label_Maker.configure(disabledforeground="#3f3f3f")
        self.Label_Maker.configure(foreground="white")
        self.Label_Maker.configure(highlightbackground="black")
        self.Label_Maker.configure(highlightcolor="white")
        self.Label_Maker.configure(text='''Made By Ginges3DPrints''')

        self.Label_title = tk.Label(self.top)
        self.Label_title.place(relx=0.323, rely=0.029, height=45, width=333)
        self.Label_title.configure(activebackground="#d9d9d9")
        self.Label_title.configure(activeforeground="black")
        self.Label_title.configure(anchor='w')
        self.Label_title.configure(background="black")
        self.Label_title.configure(compound='left')
        self.Label_title.configure(disabledforeground="#3f3f3f")
        self.Label_title.configure(font="-family {MV Boli} -size 16")
        self.Label_title.configure(foreground="white")
        self.Label_title.configure(highlightbackground="black")
        self.Label_title.configure(highlightcolor="white")
        self.Label_title.configure(text='''HuskyLens V2 Arcade''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='black',fg='white')
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

def start_up():
    HuskyArcade_support.main()

if __name__ == '__main__':
    HuskyArcade_support.main()
